config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create, :destroy, :update]
  resources :sessions, only: [:new, :create, :destroy]
  resources :projects, only: [:create, :update, :destroy]
  resources :tasks, only: [:create, :update, :destroy, :up, :down, :done] do
    get 'up', via: 'patch'
    get 'down', via: 'patch'
    post 'done', via: 'patch'
  end

  root 'start_page#home'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/registration',  to: 'users#new',    via: 'get'

end

app/models/project.rb
class Project < ActiveRecord::Base
belongs_to :user
has_many :tasks, dependent: :destroy

validates :title, length: { maximum: 70 }
validates :user_id, presence: true

end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :project
	validates :content, presence: true, length: { maximum: 70 }
	validates :project_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
has_many :projects, dependent: :destroy
has_many :tasks, through: :projects

before_save { self.email = email.downcase }
before_create :create_remember_token
validates :name, presence: true, length: {maximum: 36}
VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validates :email, presence:   true, format: { with: VALID_EMAIL_REGEX }, uniqueness: {case_sensitive: false}
has_secure_password
validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :signed_in_user

  def create
  	@project = current_user.projects.build
    respond_to do |format|
      format.html { 
        redirect_to root_path 
        @project.save
      }
      format.js
    end
  end

  def update
    @project = Project.find(params[:id])
    @project.update(project_params)
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  private

    def project_params
      params.require(:project).permit(:title)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
    else
      flash[:error] = 'Invalid email/password combination'
    end
    redirect_to root_path
  end

  def destroy
    sign_out
    redirect_to root_url
  end

end

app/controllers/start_page_controller.rb
class StartPageController < ApplicationController

  def home
  	if signed_in?
      @user = User.find(current_user.id)
      @projects = @user.projects
      @tasks = {}
      @projects.each { |p| 
        @tasks[p.id]=p.tasks.order("priority DESC");
      }
	  end
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :signed_in_user
  skip_before_filter  :verify_authenticity_token, :only => [:done]

  def create
    @task = current_user.tasks.build(task_params)
    @task.priority=@task.project.tasks.count+1
    respond_to do |format|
      format.html { 
        @task.save
        redirect_to root_path 
      }
      format.js
    end
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  def destroy
  	@task = Task.find(params[:id])
    tasks = @task.destroy.project.tasks.order(:priority)
    i = 0;
    tasks.each { |t| t.update(priority: i+=1) }
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  def up
    @task1 = Task.find(params[:task_id])
    @thistasks = @task1.project.tasks
    if @task1.priority<@thistasks.count
      @task2 = @thistasks.find_by(priority: @task1.priority+=1)
      @task2.priority-=1
      @task1.save
      @task2.save
    end
    respond_to do |format|
      format.html { 
        redirect_to root_path 
      }
      format.js
    end
  end

  def down
    @task1 = Task.find(params[:task_id])
    @thistasks = @task1.project.tasks
    if @task1.priority>1
      @task2 = @thistasks.find_by(priority: @task1.priority-=1)
      @task2.priority+=1
      @task1.save
      @task2.save
    end
    respond_to do |format|
      format.html { 
        redirect_to root_path 
      }
      format.js
    end
  end

  def done
    @task = Task.find(params[:task_id])
    @task.update_attributes(:done => params[:done])
    render nothing: true
  end

  private

    def task_params
      params.require(:task).permit(:content,:project_id,:done,:deadline)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user,   only: :show

  def new
  	@user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def signed_in_user
    unless signed_in?
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

end

app/helpers/start_page_helper.rb
module StartPageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo List</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
	<%= yield %>
<div class="container">
</body>
</html>

app/views/projects/_project.html.erb
<li class="project" id="project_<%=project.id%>" >
  <div class="project-title btn-primary">
    <%= fa_icon "calendar-o" %>
    <span class="title"><%=project.title%></span>
    <span class="input-append">
    <div class="edit-form" <%= 'hidden' if !Rails.env.test? && (project.title!="" && project.title) %> >
    <%= form_for(project, remote: true) do |f| %>
      <%= f.text_field :title, maxlength: 70, id: "input_title_#{project.id}" %>
      <%= button_tag(type: "submit", class: "btn btn-primary", id: "submit_edit_project_#{project.id}"  ) do%>
        <i class="icon-ok-circle"></i>
      <% end %>
    <% end %>
    </div>
    </span>
    <%= render partial: 'shared/udbar', locals: {target: project} %>
  </div>
  <div class="input-append taskform center">
    <%= render partial: 'tasks/task_form', locals: {pid: project} %>
  </div>
  <table class="tasks table table-bordered table-hover">
    <%= render @tasks[project.id] if project.tasks.any? %>
  </table>
</li>

app/views/projects/_project_form.html.erb
<%= form_for(current_user.projects.build, remote: true) do |f| %>
  <%= button_tag(type: "submit", class: "btn btn-large btn-primary") do %>
    <%= fa_icon "plus" %> Add TODO List
  <% end %>
<% end %>

app/views/projects/create.js.erb
<% if @project.save %>
  $(".projects").append("<%= escape_javascript(render(@project)) %>");
  $(show_bar_project("#project_<%=@project.id%>"));
  $(editfunc_project("#project_<%=@project.id%>"));
<% end %>

app/views/projects/destroy.js.erb
$("#project_<%=@project.id%>").remove();

app/views/projects/update.js.erb
var title = $("#project_<%=@project.id%>").find(".title");
var editform = $("#project_<%=@project.id%>").children('.project-title').find(".edit-form");
title.text("<%=@project.title%>");
editform.hide();
title.show();

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_udbar.html.erb
  <div class="pull-right udbar hidebar">
  <span class="edit" id="show_edit_<%= target.class.to_s.downcase %>_<%= target.id %>">
      <%= fa_icon "pencil 1x" %>
  </span>
  <span class="destroy">
  <%=link_to target, method: :delete, data: { confirm: 'Are you sure?' }, remote: true, id: "delet_#{target.class.to_s.downcase}_#{target.id}" do
      fa_icon "trash 1x"
      end %>
  </span>
  </div>

app/views/start_page/home.html.erb
<% if signed_in? %>
<div class ="row">
  <div class="span12">
    <section>
    <div class="signout_link">
    <%= link_to "Sign out", signout_path, method: "delete"%>
    </div>
      <h1 class="center">
        Hello, <%= @user.name %>
      </h1>
    </section>
      <ul class="projects">
        <%= render @projects if @user.projects.any? %>
      </ul>
      <div class="center projectform">
      <%= render 'projects/project_form' %>
      </div>
  </div>
</div>
<% else %>
<div class="row">
  <div class="span6">
  <h1> Just do it! <h1>
  <h2>Well come</h2>
    <%= form_for(:session, url: sessions_path) do |f| %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>
      <br>
      <%= f.submit "Sign in", class: "btn btn-large btn-primary"%>
    <% end %>

    <p>don't have account? <%= link_to "Sign up!", registration_path %></p>
  </div>
</div>
<% end %>

app/views/tasks/_task.html.erb
<tbody  id="task_<%=task.id%>">
<tr class="task">
    <td class="donecol">
      <%= check_box_tag "done", task.id, task.done, :class => "task-done", id: "done_#{task.id}"  %>
    </td>
    <td class="maincol">
      <%= form_for(task, remote: true) do |f| %>
      <div class="content"><%= task.content%></div>
      <div class="edit-form" hidden>
        <div class="input-append">
          <%= f.text_field :content, maxlength: 85, id: "input_content_#{task.id}" %>
          <%= button_tag(type: "submit", class: "btn btn-primary", id: "submit_edit_task_#{task.id}") do%>
            <i class="icon-ok-circle"></i>
          <% end %>
        </div>
        <div class="deadline">
          <%= f.datetime_select :deadline %>
        </div>
      </div>
      <% end %>
    </td>
  <td class="barcol">
  <%= render partial: 'shared/udbar', locals: {target: task} %>
  <div class="pull-right hidebar">
    <div class="angle">
      <%= link_to task_up_path(task), remote: true do
        fa_icon "angle-up"
      end %>
    </div>
    <div class="angle">
      <%= link_to task_down_path(task), remote: true do
        fa_icon "angle-down"
      end %>
    </div>
  </div>
  </td>
 </tr>
 </tbody>

app/views/tasks/_task_form.html.erb
<%= form_for(pid.user.tasks.build, remote: true) do |f| %>
  <%= f.hidden_field :project_id, value: pid.id %>
  <%= fa_icon "plus" %>
  <%= f.text_field :content, maxlength: 85, placeholder: "new task...", class: "inputtask", id: "input_create_task_project_#{pid.id}" %>
  <%= f.submit "Create", class: "btn btn-success btntask", id: "create_task_project_#{pid.id}" %>
<% end %>

app/views/tasks/create.js.erb
<% if @task.save %>
  $("#project_<%=@task.project.id%>").find(".tasks").prepend("<%= escape_javascript(render(@task)) %>");
  $("#project_<%=@task.project.id%>").find(".inputtask").val("");
  $(show_bar_task("#task_<%=@task.id%>"));
  $(editfunc_task("#task_<%=@task.id%>"));
  $(taskdone);
<% end %>

app/views/tasks/destroy.js.erb
$("#task_<%=@task.id%>").remove();

app/views/tasks/down.js.erb
<% if (@task2 && @task1.save && @task2.save) %>
	$("#task_<%=@task1.id%>").remove();
	$("#task_<%=@task2.id%>").after("<%= escape_javascript(render(@task1)) %>");
    $(show_bar_task("#task_<%=@task1.id%>"));
  	$(editfunc_task("#task_<%=@task1.id%>"));
  	$(taskdone);
<% end %>

app/views/tasks/up.js.erb
<% if (@task2 && @task1.save && @task2.save) %>
	$("#task_<%=@task1.id%>").remove();
	$("#task_<%=@task2.id%>").before("<%= escape_javascript(render(@task1)) %>");
    $(show_bar_task("#task_<%=@task1.id%>"));
  	$(editfunc_task("#task_<%=@task1.id%>"));
  	$(taskdone);
<% end %>

app/views/tasks/update.js.erb
var content = $("#task_<%=@task.id%>").find(".content");
var editform = $("#task_<%=@task.id%>").find(".edit-form");
content.text('<%=@task.content%>');
editform.hide();
content.show();

app/views/users/new.html.erb
<div class="row">
  <div class="span6">
    <h1>Registration</h1>

    <%= form_for(@user) do |f| %>
    
    <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name%>
      <%= f.text_field :name, maxlength: 36%>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password%>

      <%= f.label :password_confirmation, 'Confirmation'%>
      <%= f.password_field :password_confirmation %>
      <br>
      <%= f.submit "Sign up", class: "btn btn-large btn-primary"%>
    <% end %>

    <%= link_to("Sign in",root_path) %>
  </div>
</div>